development:
  adapter: postgresql
  encoding: unicode
  database: codetython_development
  pool: 5
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: codetython_test
  pool: 5
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: codetython_production
  pool: 5
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>
  host: localhost
