development:
  adapter: postgresql
  encoding: unicode
  database: codetython_development
  pool: 5
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>
  host: localhost
  port: 5432

test:
  adapter: sqlite3 
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: codetython_production
  pool: 5
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>
  host: localhost
